- name: This is composite script that creates VPN IPSec profile and tunnel on NGFW
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
   - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Add IKE crypto config to the firewall
    panos_ike_crypto_profile:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'IKE-oregon'
      dhgroup: 'group14'
      authentication: 'sha256'
      encryption: ['aes-256-cbc', '3des']
      lifetime_sec: '28800'
      commit: 'True'

  - name: Add IPSec crypto config to the firewall
    panos_ipsec_profile:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'IPSec-oregon'
      encryption: ['aes-256-cbc', '3des']
      authentication: 'sha256'
      dhgroup: 'group2'
      lifetime_hrs: '1'
      commit: 'True'

  - name: Add IKE gateway config to the firewall
    panos_ike_gateway:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'IKEGW-oregon'
      protocol_version: 'ikev1'
      interface: 'ethernet1/3'
      pasive_mode: 'True'
      liveness_check: '5'
      peer_ip_value: '34.212.247.34'
      psk: 'tCSbv34u4CB3Bp0LXdh7EzhePxmo6tHw'
      crypto_profile_name: 'IKE-oregon'
      exchange_mode: 'main'
      dead_peer_detection: 'True'
      dead_peer_detection_interval: '10'
      dead_peer_detection_retry: '3'
      commit: 'True'
    
  - name: Create Tunnel Interface tunnel4
    panos_tunnel:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      if_name: 'tunnel.4'
      ip: ["169.254.15.206/30"]
      vr_name: "default"
      zone_name: "untrust"
      comment: "IPSec connection to remote site"
      management_profile: "allow-ping"
      mtu: '1427'
      commit: 'true'

  - name: Add IPSec tunnel to IKE gateway profile
    panos_ipsec_tunnel:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'IPSecTunnel-oregon'
      tunnel_interface: 'tunnel.6'
      ike_gtw_name: 'IKEGW-oregon'
      ipsec_profile: 'IPSec-oregon'
      commit: 'False'
