- name: This is composite script that creates VPN IPSec profile and tunnel on NGFW
  hosts: my-firewall
  connection: local
  gather_facts: False

#  roles:
#    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Add IKE crypto config to the firewall
    panos_ike_crypto_profile:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'IKE-vertex'
      dhgroup: 'group14'
      authentication: 'sha256'
      encryption: ['aes-256-cbc', '3des']
      lifetime_sec: '28800'
      commit: 'False'

  - name: Add IPSec crypto config to the firewall
    panos_ipsec_profile:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'IPSec-vertex'
      encryption: ['aes-256-cbc', '3des']
      authentication: 'sha256'
      dhgroup: 'group14'
      lifetime_hrs: '1'
      commit: 'False'

  - name: Add IKE gateway config to the firewall
    panos_ike_gateway:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'IKEGW-Vertex'
      protocol_version: 'ikev2'
      interface: 'ethernet1/3'
      pasive_mode: 'True'
      liveness_check: '5'
      peer_ip_value: '192.80.70.8'
      psk: 'CHANGEME'
      crypto_profile_name: 'IKE-vertex'
      commit: 'False'
  
  
  - name: Create Tunnel Interface 'tunnel.5'
    panos_tunnel:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      if_name: tunnel.5
      ip: 192.168.27.21/30
      vr_name: default
      zone_name: ipsec_tunnel
      comment: IPSec connection to remote site
      management_profile: allow-ping

  - name: Add IPSec tunnel to IKE gateway profile
    panos_ipsec_tunnel:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'present'
      name: 'IPSecTunnel-vertex'
      tunnel_interface: 'tunnel.2'
      ike_gtw_name: 'IKEGW-vertex'
      ipsec_profile: 'IPSec-vertex'
      commit: 'False'
